server:
  port: 9997

spring:
  profiles:
    active: native
  application:
    name: configuration-server
  cloud:
    config:
      server:
        native:
          search-locations: E:/KPI/6_semestr/SMTRPZ/Cursach17061955/Cursach/springschool/configs-lab-3

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7777/eureka
  instance:
    metadata-map:
      instance-id: ${spring.application.name}:${server.port}