server:
  port: 8888    #port number

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:7777/eureka/
    healthcheck:
      enabled: true

error:
  whitelabel:
    enabled: false

logging:
  level:
    com.example.eurekaclientlab2: DEBUG
spring:
  datasource:
    url : jdbc:mysql://localhost:3306/songs_service?serverTimezone=Europe/Kiev&useSSL=false
    username : root
    password : maroussia216
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
LIVE:
  FAST:
    DIE:
      YOUNG